UnapecISO810.Projects/FoodMarket.App/Controllers/OffersController.cs
using FoodMarket.App.AgroMarketService;
using FoodMarket.App.Models;
using FoodMarket.App.Services;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FoodMarket.App.Controllers
{
    public class OffersController : Controller
    {
        private readonly OfferService _offerService;

        public OffersController()
        {
            _offerService = new OfferService(System.Web.HttpContext.Current.Session.TransactionServiceToken());
        }

        public ActionResult Index()
        {
            var offers = _offerService.GetOffers();
            return View(offers);
        }

        
    }
}

UnapecISO810.Projects/FoodMarket.App/Controllers/ProductController.cs
using FoodMarket.App.AgroMarketService;
using FoodMarket.App.Services;
using System.Web.Mvc;

namespace FoodMarket.App.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;

        public ProductController()
        {
            _productService = new ProductService(System.Web.HttpContext.Current.Session.TransactionServiceToken());
        }

        public ActionResult Index()
        {
            var products = _productService.GetProducts();
            return View(products);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Get()
        {
            var products = _productService.GetProducts();
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetUnits()
        {
            var units = _productService.GetUnits();
            return Json(units, JsonRequestBehavior.AllowGet);
        }

        //[ValidateAntiForgeryToken]
        //[HttpPost]
        //public ActionResult Create(Product product)
        //{
        //    _productService.Add(product);
        //    return RedirectToAction("Index");
        //}

    }
}

UnapecISO810.Projects/FoodMarket.App/Controllers/SellersController.cs
using FoodMarket.App.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FoodMarket.App.Controllers
{
    public class SellersController : Controller
    {
        private readonly SellingIntentionService _sellingService;

        public SellersController()
        {
            _sellingService = new SellingIntentionService(System.Web.HttpContext.Current.Session.TransactionServiceToken());
        }

        public ActionResult Index()
        {
            var intentions = _sellingService.GetSellIntentions();
            return View(intentions);
        }

        [HttpGet]
        public JsonResult GetIntention(int id)
        {
            var intentions = _sellingService.GetIntention(id);
            return Json(intentions.FirstOrDefault(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult MakeOffer(int id, int offerId)
        {
             _sellingService.CreateOffer(id, offerId);
            return Json(JsonRequestBehavior.AllowGet);
        }
    }
}

UnapecISO810.Projects/FoodMarket.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-do">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodMarket - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/pnotify.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css" />
    
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("El Mercadillo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Portada", "Index", "Home")</li>
                    <li>@Html.ActionLink("Catálogo de Productos", "Index", "Product")</li>
                    <li>@Html.ActionLink("Intenciones de Venta", "Index", "Sellers")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Nosotros <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Nosotros", "About", "Home")</li>
                            <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi Cuenta <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Shop")">Mis Intenciones de Compra</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Offers")">Mis Ofertas / Contratos</a></li>
                        </ul>
                    </li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - El Mercadillo @@ UNAPEC ISO810</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/pnotify.js"></script>
    <script src="~/Scripts/jquery.slimscroll.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.js"></script>
    <script src="~/Scripts/app.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>